### ISSUE TITLE
Warning: "... the weights as supplied won't allow parameter estimation, producing a   degenerate design matrix"

### ISSUE THREAD

**Issue by CamiArcu** [mikelove/zinbwave-deseq2#3]
Dear all;

I have encountered this warning when running the pipeline as in the vignette:
```
In getAndCheckWeights(object, modelMatrix, weightThreshold = weightThreshold) :
  for 14 row(s), the weights as supplied won't allow parameter estimation, producing a
  degenerate design matrix. These rows have been flagged in mcols(dds)$weightsFail
  and treated as if the row contained all zeros (mcols(dds)$allZero set to TRUE).
  If you are blocking for donors/organisms, consider design = ~0+donor+condition.
```

As the warning says, the problem resides at the weight values for these genes, in which, for some combination of variables evaluated (represented in a subset of cells), the weights get too small (between 1e-3 and 1e-15).

I suspect then that a small weight value may be subjected to a zero value on the count matrix. But despite the values in the equivalent positions for the count matrix correspond to zero, they are not the only genes which have zeros for this variable combination, so I am not sure what is the origin of the problem.

I also notice that the same warning appears at the zinbwave-deseq2 vignette.

I will be glad if you Mike can help me or someone have some solid knowledge about weight calculation or have already deal with this problem so I can look forward at this issue.

Thanks a lot,

Camila

**Comment by mikelove** [comment]
The problem is that the low weights correspond to positions in the design matrix for estimating beta (LFC). You can't estimate the LFC if, say, all the weights for the treated sample are 0. Any coefficient would give the same likelihood as another.
